import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/componentes/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 text-wheat ${inter.className}`}>
        <Navbar />
        <div className="h-[calc(100vh-5rem)]">
          {children}
        </div>
      </body>
    </html>
  );
}
